### ISSUE TITLE
Add ability to specify pre-launch script when trigger pipelines execution 

### ISSUE THREAD

**Issue by pditommaso** [adamrtalbot/showcase-automation#25]
It would be useful to have the ability to specify the launch pre-run script as workflow input. 

This would allow us to select the Nextflow version to be used when launching the pipeline execution for testing purposes.

**Comment by adamrtalbot** [comment]
Do you want to specify the pre-run script for all pipelines, or include it in the project YAML?

Option 1: Add it as CLI option 
```
launch_pipelines.py --config ./nextflow.config
```
Advantages: Easy to configure and adapt
Disadvantages: Annoying to implement in the automation

Option 2: Add it to pipeline YAML
```
pipelines:
  - name: hello
    url: hello
    latest: true
    config: ./pipelines/nextflow.config
    pre-run: './pipelines/pre_run.sh'
    profiles: []
```
Advantages: Easy to automate
Disadvantages: Hard to change on the fly

Option 3: Add it as ENV variable or arg 
```
launch_pipelines.py --nextflow 23.10.1
```
Advantages: Configurable and straightforward to automate
Disadvantages: Single use tool.
